on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build:
    env:
      RELEASENAME: 'v$(cat RELEASENAME)'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        # Filename is RELEASENAME + .zip
        filename: '${{ env.RELEASENAME }}.zip'
        exclusions: "*.git* /*node_modules/*"
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: '${{ env.RELEASENAME }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}